; ============================================================
; File     : globals.inc
; Purpose  : Shared EXTERN declarations for all modules.
; ============================================================

EXTERN curr_X:SBYTE
EXTERN curr_Y:SBYTE
EXTERN X_dir:SBYTE
EXTERN Y_dir:SBYTE

EXTERN MAX_WIDTH:BYTE
EXTERN MAX_HEIGHT:BYTE
EXTERN BoundaryFlag:BYTE
EXTERN UPPER_LIMIT:BYTE
EXTERN score:DWORD
EXTERN shoot_Y:SBYTE
EXTERN D_MSG:BYTE

EXTERN E1_X:SBYTE
EXTERN E1_Y:SBYTE
EXTERN E1_X_dir:SBYTE
EXTERN E1_Y_dir:SBYTE

EXTERN E2_X:SBYTE
EXTERN E2_Y:SBYTE
EXTERN E2_X_dir:SBYTE
EXTERN E2_Y_dir:SBYTE

EXTERN E3_X:SBYTE
EXTERN E3_Y:SBYTE
EXTERN E3_X_dir:SBYTE
EXTERN E3_Y_dir:SBYTE
